# Generated by Django 5.2.8 on 2025-12-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orders_id_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_json',
            field=models.TextField(default='{}'),
        ),
    ]
